version: '3'
services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"       # 外部 HTTP 用
      - "443:443"     # 外部 HTTPS 用
      - "8080:8080"   # Traefik ダッシュボード（オプション）
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro
      - ./letsencrypt:/letsencrypt

  playground:                 # `devcontainer.json`の'service'と一致させる
    container_name: 'fastapi_app'  # コンテナ名
    hostname: 'dev_user'        # ホスト名.ゲストOSのシェルに表示されるので指定している

    # 以下は他のリポジトリも全て同じ設定にしています
    build: .                  # Dockerfileがあるディレクトリ
    restart: always           # 常に再起動
    working_dir: '/workspace' # デフォルトの作業ディレクトリ
    tty: true                 # コンテナを終了させずに待たせる
    volumes:                  # ホストとゲストのディレクトリを紐づける
      - type: bind            # ホストのディレクトリをゲストにマウントさせる
        source: ../workspace  # ホストの`workspace`ディレクトリを指定
        target: /workspace    # ゲストの`/workspace`にマウントさせる
    labels:
      - "traefik.enable=true"
      # HTTPS設定
      - "traefik.http.routers.playground.rule=Host(`abe-techfolio.com`)"
      - "traefik.http.routers.playground.entrypoints=websecure"
      # TLS 有効
      - "traefik.http.routers.playground.tls=true"
      - "traefik.http.routers.playground.tls.certresolver=myresolver"
      # ミドルウェアをチェーン（先ほどの noindex と basicAuth を適用）
      # Traefik はミドルウェア basicAuth を @docker（Dockerラベル側）から探しているが、
      # 実際は .yml（@file）に定義されているため明示的に@fileをつける
      - "traefik.http.routers.playground.middlewares=noindex@file,basicAuth@file"

      # HTTP Let'tencrypt認証
      - "traefik.http.routers.playground-http.rule=Host(`abe-techfolio.com`)"
      - "traefik.http.routers.playground-http.entrypoints=web"
      
      # FastAPI (uvicorn) が内部で使用するポート（Dockerfileで CMD で指定しているポート、例:8000）
      - "traefik.http.services.playground.loadbalancer.server.port=8000"
